### ISSUE TITLE
Styles not applied

### ISSUE THREAD

**Issue by xuv** [GitbookIO/plugin-styles-less#1]
Hello

Just tried your plugin with the pdf example.

```
"plugins": ["styles-less"],
"styles": {
    "pdf": "./styles/pdf.less"
}
```

Although console says it compiled the less file to CSS, but it does not apply the styles.

If I compile myself the style to .css and change the book.json accordingly, style is properly applied.

```
"styles": {
    "pdf": "./styles/pdf.css"
}
```

**Comment by SamyPesse** [comment]
it'll fix with latest GitBook version( https://github.com/GitbookIO/gitbook/commit/becd027563f361e7dc6824d18c58978b08aa6118)

**Comment by xuv** [comment]
Ok. Thx. 
Sorry to ask here. But any idea how to run that latest version from `master` locally.
Can't find in the doc how to run your own version of Gitbook.

**Comment by xuv** [comment]
Don't bother answering. I found the answer to that question at the bottom of the Gitbook Readme.
